### ISSUE TITLE
Portal App Prototype (META TASK)

### ISSUE THREAD

**Issue by bastiion** [fsfw-dresden/schulstick-portal#1]
We are developing an usb flash drive linux live system for students and makers, our most
used variant being the "schulstick". From practical use during recent years, we have identified some items to increase
usability. That's why we want to implement a portal app that helps the user to find applications from the extensive software selection that comes preinstalled with the system and assists them learning to use them for their workflows. Some features it should have: 
  
- [ ] opens after initial Schulstick boot
- [x] has multi-language support from the beginning
- [ ] welcomes with avatar Glibber guiding children
    - [x] interactive wizard for skill level and interest
- [ ] offers (secondary) tabs (?) for
    - [ ] Feedback
    - [ ] Support
    - [ ] Install
    - [ ] News
    - [ ] Features

The portal app should
- [ ] be responsive & intuitive
- [ ] live in systray and able to show shaped notifications with input widgets
- [ ] conserve memory when in background (hotloading resources / standby mode)
- [ ] use a rapid development GUI framework with fluid layout
- [x] ~~PyQt6 ? (non-commercial use)~~
- [x]  PyQt5 !
- [ ] PyFluentWidgets ? QML? WebAssembly?
- [ ] (have animated cartoon avatars? see
attached mockups of how the learning
assistant functionality (which is another
project, but integrated with this one) could look
and feel)
Ideal Candidate:
- [ ] has routine in completing projects well
- [ ] has a passion for Open Educational
Resources and Open Source Software
